apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mykubeapps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mykubeapps.selectorLabels" . | nindent 8 }}
        app: transmission
    spec:
      initContainers:
        - name: config-transmission
          image: docker.io/ubuntu:groovy
          command: ["/init-transmission/init-transmission.sh"]
          volumeMounts:
            - mountPath: /init-transmission
              name: init-files-transmission
            - mountPath: /transmission-config
              name: mykubeapps-volume
              subPath: "config/transmission"
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: transmission-config
          image: "docker.io/linuxserver/transmission:{{ .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.transmission.container.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: trans-port
              containerPort: {{ .Values.transmission.container.port }}
              protocol: TCP
          volumeMounts:
            - name: mykubeapps-volume
              mountPath: "/config"
              subPath: "config/transmission"
            - name: mykubeapps-volume
              mountPath: "/downloads"
              subPath: "Downloads/Complete"
      volumes:
        - name: mykubeapps-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        - name: init-files-transmission
          configMap:
            defaultMode: 493
            name: init-transmission-cm
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
